name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  retrofit: ^4.1.0
  dio: ^5.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.0.2+1
  dio_cookie_manager: ^3.1.1
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  lottie: ^3.1.0
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  app_settings: ^5.1.1
  theme_provider: ^0.6.0
  bot_toast: ^4.1.3
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/icons/
